# ================================================================
# SaaS Seeder — New Project Scaffolding Script
# ================================================================
# This script transforms the template into a real SaaS project.
# Run ONCE when starting a new project.
#
# What it does:
#   1. Creates the database with proper charset/collation
#   2. Runs the platform migration (auth, RBAC, franchises, etc.)
#   3. Applies project-specific schema (if provided)
#   4. Applies seed data (if provided)
#   5. Creates the first super admin user
#   6. Creates the first franchise
#   7. Generates .env from .env.example with fresh secrets
#
# Prerequisites:
#   - WAMP/MySQL running
#   - PHP 8.2+ available
#   - composer install already run
#   - Project requirements in docs/project-requirements/
#   - (Optional) Project schema in database/schema/core-schema.sql
# ================================================================

param(
    [string]$ProjectName = "",
    [string]$DbName = "",
    [string]$MysqlPath = "C:\wamp64\bin\mysql\mysql8.0.39\bin\mysql.exe",
    [string]$PhpPath = "C:\wamp64\bin\php\php8.2.29\php.exe"
)

# ── Colours ──
function Write-Step($msg) { Write-Host "  [STEP] $msg" -ForegroundColor Cyan }
function Write-Ok($msg) { Write-Host "  [OK]   $msg" -ForegroundColor Green }
function Write-Err($msg) { Write-Host "  [ERR]  $msg" -ForegroundColor Red }
function Write-Info($msg) { Write-Host "  [INFO] $msg" -ForegroundColor Yellow }

Write-Host ""
Write-Host "========================================" -ForegroundColor White
Write-Host " SaaS Seeder — Project Scaffolding" -ForegroundColor White
Write-Host "========================================" -ForegroundColor White
Write-Host ""

# ── Step 0: Collect project info ──
if (-not $ProjectName) {
    $ProjectName = Read-Host "Project name (e.g. 'School Manager', 'Restaurant POS')"
}
if (-not $DbName) {
    $suggestion = ($ProjectName -replace '[^a-zA-Z0-9]', '_').ToLower()
    $DbName = Read-Host "Database name [$suggestion]"
    if (-not $DbName) { $DbName = $suggestion }
}

$SessionPrefix = ($DbName -replace '[^a-zA-Z0-9_]', '') + "_"

Write-Host ""
Write-Info "Project:  $ProjectName"
Write-Info "Database: $DbName"
Write-Info "Session:  $SessionPrefix"
Write-Host ""

# ── Step 1: Create database ──
Write-Step "Creating database: $DbName"
& $MysqlPath -u root -e "CREATE DATABASE IF NOT EXISTS ``$DbName`` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" 2>&1
if ($LASTEXITCODE -ne 0) { Write-Err "Database creation failed!"; exit 1 }
Write-Ok "Database created"

# ── Step 2: Run platform migration ──
Write-Step "Running platform migration (auth, RBAC, franchises, settings...)"
$migrationFile = "docs\seeder-template\migration.sql"
if (-not (Test-Path $migrationFile)) { Write-Err "Migration file not found: $migrationFile"; exit 1 }
& $MysqlPath -u root $DbName < $migrationFile 2>&1
if ($LASTEXITCODE -ne 0) { Write-Err "Platform migration failed!"; exit 1 }
Write-Ok "Platform tables created (16 tables + stored procedures)"

# ── Step 3: Apply project-specific schema (if exists) ──
$projectSchema = "database\schema\core-schema.sql"
if (Test-Path $projectSchema) {
    Write-Step "Applying project-specific schema: $projectSchema"
    & $MysqlPath -u root $DbName < $projectSchema 2>&1
    if ($LASTEXITCODE -ne 0) { Write-Err "Project schema failed!"; exit 1 }
    Write-Ok "Project schema applied"
} else {
    Write-Info "No project schema found at $projectSchema (skipping)"
}

# ── Step 4: Apply seed data (if exists) ──
$seedFile = "database\schema\seed-data.sql"
if (Test-Path $seedFile) {
    Write-Step "Applying seed data: $seedFile"
    & $MysqlPath -u root $DbName < $seedFile 2>&1
    if ($LASTEXITCODE -ne 0) { Write-Err "Seed data failed!"; exit 1 }
    Write-Ok "Seed data applied"
} else {
    Write-Info "No seed data found at $seedFile (skipping)"
}

# ── Step 5: Generate .env with fresh secrets ──
Write-Step "Generating .env with fresh secrets"
$cookieKey = & $PhpPath -r "echo bin2hex(random_bytes(32));"
$pepper = & $PhpPath -r "echo bin2hex(random_bytes(32));"
$jwtKey = & $PhpPath -r "echo bin2hex(random_bytes(32));"

$envContent = @"
# $ProjectName — Environment Configuration
# Generated by scaffold-project.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')

# Database
DB_HOST=localhost
DB_PORT=3306
DB_NAME=$DbName
DB_USER=root
DB_PASSWORD=

# Application
APP_ENV=development
APP_URL=http://localhost:8000

# Cookie
COOKIE_DOMAIN=localhost
COOKIE_ENCRYPTION_KEY=$cookieKey

# Password Security
PASSWORD_PEPPER=$pepper

# JWT
JWT_SECRET_KEY=$jwtKey

# CORS
CORS_ALLOWED_ORIGINS=http://localhost:8000
"@

$envContent | Out-File -FilePath ".env" -Encoding UTF8 -NoNewline
Write-Ok ".env generated with fresh secrets"

# ── Step 6: Update session prefix ──
Write-Step "Setting session prefix to: $SessionPrefix"
$sessionFile = "src\config\session.php"
(Get-Content $sessionFile) -replace "define\('SESSION_PREFIX', '.*?'\)", "define('SESSION_PREFIX', '$SessionPrefix')" | Set-Content $sessionFile
Write-Ok "Session prefix updated"

# ── Step 7: Update app name in system settings ──
Write-Step "Setting app name in database: $ProjectName"
$escapedName = $ProjectName -replace "'", "''"
& $MysqlPath -u root $DbName -e "UPDATE tbl_system_settings SET setting_value = '$escapedName' WHERE setting_key = 'app_name';" 2>&1
Write-Ok "App name updated in tbl_system_settings"

# ── Summary ──
Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host " Scaffolding Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Next steps:" -ForegroundColor White
Write-Host "    1. Visit http://localhost:8000/super-user-dev.php" -ForegroundColor White
Write-Host "       to create the first super admin account" -ForegroundColor Gray
Write-Host "    2. DELETE super-user-dev.php after creating the admin" -ForegroundColor Yellow
Write-Host "    3. Sign in at http://localhost:8000/sign-in.php" -ForegroundColor White
Write-Host "    4. Update CLAUDE.md with project-specific details" -ForegroundColor White
Write-Host "    5. Place your logo at:" -ForegroundColor White
Write-Host "       public/assets/images/branding/logo-light.png" -ForegroundColor Gray
Write-Host ""
Write-Host "  Platform tables created:" -ForegroundColor Cyan
Write-Host "    tbl_franchises          — tenant/organization records" -ForegroundColor Gray
Write-Host "    tbl_users               — user accounts (Argon2ID)" -ForegroundColor Gray
Write-Host "    tbl_permissions         — permission definitions" -ForegroundColor Gray
Write-Host "    tbl_global_roles        — role definitions" -ForegroundColor Gray
Write-Host "    tbl_global_role_permissions — role-permission mapping" -ForegroundColor Gray
Write-Host "    tbl_franchise_role_overrides — per-tenant role overrides" -ForegroundColor Gray
Write-Host "    tbl_user_roles          — user-role assignments" -ForegroundColor Gray
Write-Host "    tbl_user_permissions    — user-level permission overrides" -ForegroundColor Gray
Write-Host "    tbl_user_sessions       — JWT session tracking" -ForegroundColor Gray
Write-Host "    tbl_login_attempts      — brute-force protection" -ForegroundColor Gray
Write-Host "    tbl_audit_log           — immutable audit trail" -ForegroundColor Gray
Write-Host "    tbl_system_settings     — global system config" -ForegroundColor Gray
Write-Host "    tbl_franchise_settings  — per-tenant config" -ForegroundColor Gray
Write-Host "    tbl_notifications       — in-app notifications" -ForegroundColor Gray
Write-Host "    tbl_file_uploads        — uploaded file metadata" -ForegroundColor Gray
Write-Host "    tbl_api_signup_requests — franchise onboarding queue" -ForegroundColor Gray
Write-Host ""
